/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifce.space;

import javax.swing.JOptionPane;
import net.jini.space.*;
import net.jini.core.entry.*;
import br.edu.ifce.space.tuplas.*;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

/**
 *
 * @author brenorm
 */
public class FinalProjectGUI2 extends javax.swing.JFrame {
    
    public static FinalProjectTuplasManager tuplaManager;
    

    /**
     * Creates new form FinalProjectGUI2
     */
    public FinalProjectGUI2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRadioButton1.setText("Ambiente");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Dispositivo");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Criar!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ambientes Criados");

        jLabel2.setText("Dispositivos Criados");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton4.setText("Visualizar Historico");

        jButton3.setText("Alternar Dispositivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(217, 42, 42));
        jButton2.setForeground(new java.awt.Color(254, 254, 254));
        jButton2.setText("Deletar Ambiente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Ao criar novos dispositivos, voce deve selecionar previamente o ambiente no seletor abaixo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
            int totalAmbientes = tuplaManager.getTotalAmbientes();
            int functionReturn = tuplaManager.createAmbiente(totalAmbientes);
            if(functionReturn == 0){
                totalAmbientes = tuplaManager.getTotalAmbientes();
                jComboBox1.removeAllItems();
                String existingAmbId;
                String searchQuery;
                List<String> removedAmbs = tuplaManager.getRemovedAmbs();
                for(int i = 1; i <= totalAmbientes; i++){
                    searchQuery = "amb" + i;
                    if(removedAmbs != null){
                        if(removedAmbs.contains(searchQuery) == false){
                            existingAmbId = tuplaManager.getTuplaAmbiente(searchQuery);
                            jComboBox1.addItem(existingAmbId);
                        }                        
                    } else {
                            existingAmbId = tuplaManager.getTuplaAmbiente(searchQuery);
                            jComboBox1.addItem(existingAmbId);       
                    }

                }
                System.out.println("Total de ambientes: " + totalAmbientes);
            }
        } else if(jRadioButton2.isSelected()){
            int selectedAmbIndex = jComboBox1.getSelectedIndex();
            if(selectedAmbIndex != -1){
                String selectedAmb = jComboBox1.getItemAt(selectedAmbIndex);
                int dispNum = tuplaManager.getTotalDispositivos();
                if(dispNum != -5){
                    int returnedValue = tuplaManager.CreateDisp(dispNum, selectedAmb);
                    if(returnedValue == 0){
                        dispNum = tuplaManager.getTotalDispositivos();
                        jComboBox2.removeAllItems();
                        tuplaDispositivo existingDisp;
                        String searchQuery;
                        for(int i = 1; i <= dispNum; i++){
                            searchQuery = "disp" + i;
                            existingDisp = tuplaManager.getDisp(searchQuery);
                            if(existingDisp != null){
                                String dispString = existingDisp.Id + ". Ambiente Relacionado: " + existingDisp.currentAmbiente;
                                jComboBox2.addItem(dispString);
                            }
                        }
                        System.out.println("Total de Dispositivos: " + dispNum);
                    } else {
                        JOptionPane.showMessageDialog(null, "Voce deve selecionar um ambiente ao qual deseja relacionar seu dispositivo!");
                    }
                }

                
            } else {
             JOptionPane.showMessageDialog(null, "Voce deve selecionar um ambiente!");   
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o que voce deseja criar");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedAmbIndex = jComboBox1.getSelectedIndex();
            if(selectedAmbIndex != -1){
                String ambId = jComboBox1.getItemAt(selectedAmbIndex);
                int hasRemoved = tuplaManager.dropAmbiente(ambId);
                if(hasRemoved == 0){
                    int totalAmbientes = tuplaManager.getTotalAmbientes();
                    jComboBox1.removeAllItems();
                    String existingAmbId;
                    String searchQuery;
                    List<String> removedAmbs = tuplaManager.getRemovedAmbs();
                    for(int i = 1; i <= totalAmbientes; i++){
                        searchQuery = "amb" + i;
                        if(removedAmbs != null){
                            if(removedAmbs.contains(searchQuery) == false){
                                existingAmbId = tuplaManager.getTuplaAmbiente(searchQuery);
                                jComboBox1.addItem(existingAmbId);
                            }                        
                        } else {
                                existingAmbId = tuplaManager.getTuplaAmbiente(searchQuery);
                                jComboBox1.addItem(existingAmbId);       
                        }

                    }
                    System.out.println("Total de ambientes: " + totalAmbientes); 
                    }
            } else {
                JOptionPane.showMessageDialog(null, "Voce deve selecionar o ambiente que deseja excluir");
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedAmbIndex = jComboBox1.getSelectedIndex();
        int selectedDispIndex = jComboBox2.getSelectedIndex();
        if(selectedAmbIndex != -1 && selectedDispIndex != -1){
            String ambId = jComboBox1.getItemAt(selectedAmbIndex);
            String dispId = jComboBox2.getItemAt(selectedDispIndex);
            String[] partialDispString = dispId.split(Pattern.quote("."));
            dispId = partialDispString[0];
            System.out.println(dispId);
            int returnedValue = tuplaManager.changeDispAmb(dispId, ambId);
            if(returnedValue == 0){
                int dispNum = tuplaManager.getTotalDispositivos();
                jComboBox2.removeAllItems();
                tuplaDispositivo existingDisp;
                String searchQuery;
                for(int i = 1; i <= dispNum; i++){
                    searchQuery = "disp" + i;
                    existingDisp = tuplaManager.getDisp(searchQuery);
                    if(existingDisp != null){
                        String dispString = existingDisp.Id + ". Ambiente Relacionado: " + existingDisp.currentAmbiente;
                        jComboBox2.addItem(dispString);
                    }
                }
                JOptionPane.showMessageDialog(null, "Ambiente do Dispositivo alterado com sucesso!");
            }
        } else {
           JOptionPane.showMessageDialog(null, "Voce deve selecionar o ambiente e o dispositivo que deseja alternar"); 
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalProjectGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalProjectGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalProjectGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalProjectGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
            System.out.println("Bem vindo ao projeto 4. Tentando encontrar o espaço de tuplas...");
            tuplaManager = new FinalProjectTuplasManager();
            if(tuplaManager.space == null){
                System.out.println("JavaSpace nao encontrado, por favor cheque se o serviço esta no ar. Encerrando...");
                System.exit(-1);
            }
            
            System.out.println("JavaSpace encontrado, criando tuplas contadoras");
            boolean ambCounterCreated = tuplaManager.createAmbienteCounter();
            boolean dispCounterCreated = tuplaManager.createDispCounter();
            if(ambCounterCreated && dispCounterCreated){
                System.out.println("Tuplas contadoras criadas! Iniciando GUI");
                int totalAmb = tuplaManager.getTotalAmbientes();
                int totalDisp = tuplaManager.getTotalDispositivos();
                System.out.println("Total de ambientes criados: " + totalAmb);
                System.out.println("Total de dispositivos criados: " + totalDisp);
            } else {
                System.out.println("Erro ao criar tuplas contadoras. Encerrando...");
                System.exit(-1);
            }
        } catch (Exception e){
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalProjectGUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables

}
